# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  script:
  - hugo
  except:
  - master

pages:
  stage: deploy
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

assets:
  stage: deploy
  image:
    name: pandoc/latex:2.6
    entrypoint: ["/bin/sh", "-c"]
  script:
    - apk add bash
    - chmod +x ci-build.sh
    - /bin/sh -c ci-build.sh
