stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

full:
  stage: deploy
  before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
deploy_staging:
  type: deploy
  environment:
    name: staging
    url: science.lesueur.nz
  script:
    - ssh finn@45.56.84.202 "cd /srv/science.lesueur.nz/ && git checkout master && git pull origin master --recurse-submodules && exit"
    - ssh finn@45.56.84.202 "cd /srv/science.lesueur.nz/ && sh build.sh"
    - ssh finn@45.56.84.202 "cd /srv/science.lesueur.nz/ && rm -rf public/"
    - ssh finn@45.56.84.202 "cd /srv/science.lesueur.nz/ && hugo && exit"
  only:
    - master
  artifacts:
    paths:
    - public
