# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry

stages:
  - test
  - build
  # - deploy
  # - assets

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  image: registry.gitlab.com/pages/hugo:latest
  stage: test
  script:
  - hugo
  except:
  - master

# assets:
#   stage: assets
#   image:
#     name: pandoc/latex:2.6
#     entrypoint: ["/bin/sh", "-c"]
#   before_script:
#     - apk add bash
#     - apk add zip
#     - chmod +x ci-build.sh
#   script:
#     - ./ci-build.sh
#   artifacts:
#     paths:
#     - public

# pages:
#   image: registry.gitlab.com/pages/hugo:latest
#   stage: deploy
#   script:
#   - hugo
#   artifacts:
#     paths:
#     - public
#   only:
#   - master

full:
  stage: build
  image:
    name: klakegg/hugo:pandoc
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - apk add bash
    - apk add zip
    - chmod +x ci-build.sh
  script:
    - ./ci-build.sh
    - hugo
  artifacts:
    paths:
    - public