baseurl       = "http://putaiao.test"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title         = "Pūtaiao with LSF"
canonifyurls  = true
uglyurls      = false
staticDir     = ["static"]

DefaultContentLanguage  = "en"
theme                   = "hugo-spartan"
metaDataFormat          = "yaml"
pygmentsUseClasses      = true
pygmentCodeFences       = true
enableGitInfo           = true

[markup.goldmark.renderer]
  unsafe  = true

[permalinks]
  post = "/:slug/"

[Params]
  subtitle    = "Pūtaiao Courses taught by Finn LeSueur"
  logo        = "logo.png"
  favicon     = "favicon.png"
  dateFormat  = "January 2, 2006"
  commit      = true
  rss         = true
  comments    = false

[Author]
  name    = "Finn LeSueur"
  email   = "lsf@cashmere.school.nz"
  gitlab  = "Finnito"
