baseurl = "https://finnito.gitlab.io/science/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Science by LSF"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Science Courses taught by Finn LeSUeur"
  logo = "static/logo.png"
  favicon = "static/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = false

[Author]
  name = "Finn LeSueur"
  email = "lsf@cashmere.school.nz"
  gitlab = "Finnito"


# ====================
# 9SCIE
# ====================
[[menu.main]]
    name = "9SCIE"
    url = "page/9scie"
    weight = 1

# ====================
# 10SCIE
# ====================
[[menu.main]]
    name = "10SCIE"
    url = "/10scie"
    weight = 2

[[menu.main]]
    parent = "10SCIE"
    name = "Fire & Fuels"
    url = "10scie/fire-and-fuels"
    weight = 5

# ====================
# 11SCIE
# ====================
[[menu.main]]
    name = "11SCI"
    url = ""
    weight = 3

# ====================
# 12PHY
# ====================
[[menu.main]]
    name = "12PHY"
    url = ""
    weight = 4

# ====================
# 13PHY
# ====================
[[menu.main]]
    name = "13PHY"
    url = ""
    weight = 5
