baseurl = "https://science.lesueur.nz"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Science with LSF"
canonifyurls  = true
uglyurls = true
staticDir = ["static", "content"]

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Science Courses taught by Finn LeSueur"
  logo = "logo.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = false

[Author]
  name = "Finn LeSueur"
  email = "lsf@cashmere.school.nz"
  gitlab = "Finnito"


# ====================
# 9SCIE
# ====================
[[menu.main]]
    name = "9SCIE"
    url = "page/9scie"
    weight = 1

# ====================
# 10SCIE
# ====================
[[menu.main]]
    name = "10SCIE"
    url = "/10scie"
    weight = 2

[[menu.main]]
    parent = "10SCIE"
    name = "Fire & Fuels"
    url = "10scie/fire-and-fuels"
    weight = 5

[[menu.main]]
    parent = "10SCIE"
    name = "Geology"
    url = "10scie/geology"
    weight = 6

# ====================
# 11SCIE
# ====================
[[menu.main]]
    name = "11SCI"
    url = ""
    weight = 3

# ====================
# 12PHY
# ====================
[[menu.main]]
    name = "12PHY"
    url = ""
    weight = 4

# ====================
# 13PHY
# ====================
[[menu.main]]
    name = "13PHY"
    url = ""
    weight = 5
