baseurl = "https://science.lesueur.nz"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Science with LSF"
canonifyurls  = true
uglyurls = false
staticDir = ["static"]

DefaultContentLanguage = "en"
theme = "hugo-spartan"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Science Courses taught by Finn LeSueur"
  logo = "logo.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = false

[Author]
  name = "Finn LeSueur"
  email = "lsf@cashmere.school.nz"
  gitlab = "Finnito"


# ====================
# HOME
# ====================
[[menu.main]]
   name = "Home"
   url = "/"
   weight = 1

# ====================
# 9SCIE
# ====================
# [[menu.main]]
#    name = "9SCIE"
#    url = "/9scie/"
#    weight = 2

# ====================
# 10SCIE
# ====================
[[menu.main]]
    name = "10SCIE"
    url = "/10scie/"
    weight = 3

[[menu.main]]
    parent = "10SCIE"
    name = "Fire & Fuels"
    url = "10scie/5-fire-and-fuels/"
    weight = 5

[[menu.main]]
    parent = "10SCIE"
    name = "Geology"
    url = "10scie/6-geology/"
    weight = 6

# ====================
# 11SCIE
# ====================
[[menu.main]]
    name = "11SCI"
    url = "/11sci/"
    weight = 4

[[menu.main]]
    parent = "11SCI"
    name = "Genetics"
    url = "11sci/5-genetics/"
    weight = 5

# ====================
# 12PHY
# ====================
[[menu.main]]
    name = "12PHY"
    url = "/12phy/"
    weight = 5

[[menu.main]]
    parent = "12PHY"
    name = "Electricity"
    url = "12phy/3-electricity/"
    weight = 3

# ====================
# 13PHY
# ====================
#[[menu.main]]
#    name = "13PHY"
#    url = ""
#    weight = 6
