name: Deploy to Linode Server
on: []

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: rsync-with-ssh-github-actions
        uses: BuildPC/rsync-with-ssh-github-actions@1.0.1
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            host: ${{ secrets.SERVER_IP }}
            port: ${{ secrets.SERVER_PORT }}
            user: ${{ secrets.SERVER_USER }}
            ssh_before: |
              cd /srv/science.lesueur.nz/
              git checkout master
              git pull origin master --recurse-submodules
              bash build.sh
